USE [Powersoft_YASOTHA]
GO
/****** Object:  UserDefinedFunction [dbo].[Fun_YourAttn1]    Script Date: 25/03/2023 21:51:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---select * from Fun_Ins_AdvisorIncentive()
create function [dbo].[Fun_Ins_AdvisorIncentive] (

)  
returns Table  
return  
(  
--declare @Fdate as datetime  
--declare @Tdate as datetime  
--set @Fdate='2014-05-01'  
--set @Tdate ='2014-05-31'  
SELECT   
sum(SYNTH_OIL_SALES_Slab1) AS SYNTH_OIL_SALES_Slab1 ,sum(SYNTH_OIL_SALES_Slab2 )  AS  SYNTH_OIL_SALES_Slab2,sum(SYNTH_OIL_SALES_Slab3 ) SYNTH_OIL_SALES_Slab3
,sum(PSAMC_INC_Slab1 )  AS PSAMC_INC_Slab1,sum(PSAMC_INC_Slab2 )   AS PSAMC_INC_Slab2,sum(PSAMC_INC_Slab3 )   AS PSAMC_INC_Slab3
,sum(CARBON_CLEANING_Slab1 )  AS CARBON_CLEANING_Slab1,sum(CARBON_CLEANING_Slab2 )  AS  CARBON_CLEANING_Slab2,sum(CARBON_CLEANING_Slab3 )   AS CARBON_CLEANING_Slab3
,sum(WAX_POLISH_Slab1 )   AS WAX_POLISH_Slab1,sum(WAX_POLISH_Slab2 )   AS WAX_POLISH_Slab2,sum(WAX_POLISH_Slab3 )   AS WAX_POLISH_Slab3
,sum(WAX_COATING_Slab1 )   AS WAX_COATING_Slab1,sum(WAX_COATING_Slab2 )   AS WAX_COATING_Slab2,sum(WAX_COATING_Slab3 )   AS WAX_COATING_Slab3
,sum(INSURANCE_Slab1 )   AS INSURANCE_Slab1,sum(INSURANCE_Slab2 )   AS INSURANCE_Slab2,sum(INSURANCE_Slab3 )   AS INSURANCE_Slab3
,sum(GS_INC_Slab1 )   AS GS_INC_Slab1,sum(GS_INC_Slab2 )   AS GS_INC_Slab2,sum(GS_INC_Slab3 )  AS  GS_INC_Slab3
,sum(LABOUR_Slab1 )   AS LABOUR_Slab1,sum(LABOUR_Slab2 )  AS  LABOUR_Slab2,sum(LABOUR_Slab3 )   AS LABOUR_Slab3
,sum(SPARES_Slab1 )   AS SPARES_Slab1,sum(SPARES_Slab2 )   AS SPARES_Slab2,sum(SPARES_Slab3 )  AS  SPARES_Slab3


 FROM (
 SELECT
      CASE WHEN JOB_NAME='SYNTHETIC OIL SALES' and slab1='0 TO 9' THEN Slab1_Amount ELSE 0 END AS SYNTH_OIL_SALES_Slab1
 ,CASE WHEN JOB_NAME='SYNTHETIC OIL SALES'and slab2='10 TO 25' THEN Slab2_Amount ELSE 0 END AS SYNTH_OIL_SALES_Slab2
 ,CASE WHEN JOB_NAME='SYNTHETIC OIL SALES' and slab3='ABOVE 26'THEN Slab3_Amount ELSE 0 END AS SYNTH_OIL_SALES_Slab3
 ,CASE WHEN JOB_NAME='PS AMC INC' and slab1='0 TO 9' THEN Slab1_Amount ELSE 0 END AS PSAMC_INC_Slab1
,CASE WHEN JOB_NAME='PS AMC INC' and slab2='10 TO 20' THEN Slab2_Amount ELSE 0 END AS PSAMC_INC_Slab2
,CASE WHEN JOB_NAME='PS AMC INC' and slab3='ABOVE 21' THEN Slab3_Amount ELSE 0 END AS PSAMC_INC_Slab3
,CASE WHEN JOB_NAME='CARBON CLEANING' and slab1='0 TO 25'THEN Slab1_Amount ELSE 0 END AS CARBON_CLEANING_Slab1
,CASE WHEN JOB_NAME='CARBON CLEANING' and slab2='26 TO 50'THEN Slab2_Amount ELSE 0 END AS CARBON_CLEANING_Slab2
,CASE WHEN JOB_NAME='CARBON CLEANING' and slab3='ABOVE 50' THEN Slab3_Amount ELSE 0 END AS CARBON_CLEANING_Slab3
,CASE WHEN JOB_NAME='WAX POLISH'and slab1='0 TO 14' THEN Slab1_Amount ELSE 0 END AS WAX_POLISH_Slab1
,CASE WHEN JOB_NAME='WAX POLISH'and slab2='15 TO 50' THEN Slab2_Amount ELSE 0 END AS WAX_POLISH_Slab2
,CASE WHEN JOB_NAME='WAX POLISH'and slab3='ABOVE 50' THEN Slab3_Amount ELSE 0 END AS WAX_POLISH_Slab3
,CASE WHEN JOB_NAME='WAX COATING'and slab1='0 TO 9' THEN Slab1_Amount ELSE 0 END AS WAX_COATING_Slab1
,CASE WHEN JOB_NAME='WAX COATING'and slab2='10 TO 20' THEN Slab2_Amount ELSE 0 END AS WAX_COATING_Slab2
,CASE WHEN JOB_NAME='WAX COATING'and slab3='ABOVE 20' THEN Slab3_Amount ELSE 0 END AS WAX_COATING_Slab3 
,CASE WHEN JOB_NAME='INSURANCE' and slab1='0 TO 4'THEN Slab1_Amount ELSE 0 END AS INSURANCE_Slab1
,CASE WHEN JOB_NAME='INSURANCE' and slab2='5 TO 15'THEN Slab2_Amount ELSE 0 END AS INSURANCE_Slab2
,CASE WHEN JOB_NAME='INSURANCE' and slab3='ABOVE 15'THEN Slab3_Amount ELSE 0 END AS INSURANCE_Slab3
,CASE WHEN JOB_NAME='GS INC' and slab1='(0 TO 24) 'THEN Slab1_Amount ELSE 0 END AS GS_INC_Slab1
,CASE WHEN JOB_NAME='GS INC' and slab2=' (25 TO 50)'THEN Slab2_Amount ELSE 0 END AS GS_INC_Slab2
,CASE WHEN JOB_NAME='GS INC' and slab3='(ABOVE 50)'THEN Slab3_Amount ELSE 0 END AS GS_INC_Slab3
,CASE WHEN JOB_NAME='LABOUR'and slab1='0 TO .6L' THEN Slab1_Amount ELSE 0 END AS LABOUR_Slab1
,CASE WHEN JOB_NAME='LABOUR'and slab2='0.61L TO 1.25L' THEN Slab2_Amount ELSE 0 END AS LABOUR_Slab2
,CASE WHEN JOB_NAME='LABOUR'and slab3='ABOVE 1.25L' THEN Slab3_Amount ELSE 0 END AS LABOUR_Slab3
,CASE WHEN JOB_NAME='SPARES' and slab1='0 TO 0.99L'THEN Slab1_Amount ELSE 0 END AS SPARES_Slab1
,CASE WHEN JOB_NAME='SPARES' and slab2='1.0 L TO 1.75 L'THEN Slab2_Amount ELSE 0 END AS SPARES_Slab2
,CASE WHEN JOB_NAME='SPARES' and slab3='ABOVE 1.75 L'THEN Slab3_Amount ELSE 0 END AS SPARES_Slab3

FROM [Powersoft_YASOTHA].[dbo].Ins_OtherIncentive_Master
) AS P
)
 